/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Krissy' at '6/15/16 4:02 PM' with Gradle 2.13
 *
 * @author Krissy, @date 6/15/16 4:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
