/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examdatabase;

import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krissy
 */
public final class GUIapp extends javax.swing.JFrame {
    
    String months[] = {
      "Jan", "Feb", "Mar", "Apr",
      "May", "Jun", "Jul", "Aug",
      "Sep", "Oct", "Nov", "Dec"};
    
    DefaultComboBoxModel  programmeBoxModel = new DefaultComboBoxModel();
    DefaultComboBoxModel  paperCodeBoxModel = new DefaultComboBoxModel();
    DefaultComboBoxModel  facultyBoxModel = new DefaultComboBoxModel();
    DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form GUIapp
     */
    public GUIapp() {
        initComponents();
        setComboBox();
        examTable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        sessionBox = new javax.swing.JComboBox<>();
        dateField = new javax.swing.JTextField();
        venueField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        icField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        attendanceBox = new javax.swing.JComboBox<>();
        statusBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tableNumberField = new javax.swing.JTextField();
        warningMessage = new javax.swing.JLabel();
        nameHelp = new javax.swing.JLabel();
        nameHelp1 = new javax.swing.JLabel();
        nameHelp2 = new javax.swing.JLabel();
        facultyBox = new javax.swing.JComboBox<>();
        programmeBox = new javax.swing.JComboBox<>();
        paperCodeBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        examTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        searchButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        idField1 = new javax.swing.JTextField();
        icField1 = new javax.swing.JTextField();
        nameField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        warningMessage1 = new javax.swing.JLabel();
        nameHelp6 = new javax.swing.JLabel();
        nameHelp7 = new javax.swing.JLabel();
        nameHelp8 = new javax.swing.JLabel();
        programmeBox2 = new javax.swing.JComboBox<>();
        facultyBox2 = new javax.swing.JComboBox<>();
        paperCodeBox2 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        markTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        statusMessage = new javax.swing.JLabel();
        restoreButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        yearBox = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sessionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AM", "PM" }));

        venueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Session:");

        jLabel17.setText("Date:");

        jLabel18.setText("Venue:");

        jLabel15.setText("Programme: ");

        jLabel14.setText("Faculty:");

        jLabel13.setText("Paper Code:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        icField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        nameField.setToolTipText("");
        nameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameField.setName(""); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Student Name:");

        jLabel11.setText("Student IC:");

        jLabel12.setText("Student ID:");

        jLabel1.setText("Status:");

        jLabel2.setText("Attendance:");

        attendanceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Absent", "Present" }));

        statusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Legal", "Barred", "Exempted" }));

        jLabel3.setText("Table Number:");

        tableNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNumberFieldActionPerformed(evt);
            }
        });

        warningMessage.setForeground(new java.awt.Color(255, 0, 0));

        nameHelp.setText("[?]");
        nameHelp.setToolTipText("<html>\n<pre>\nExample\n '200%'\t\tFinds any values that start with 200\n '%200%'\tFinds any values that have 200 in any position\n '_00%'\t\tFinds any values that have 00 in the second and third positions\n '2_%_%'\tFinds any values that start with 2 and are at least 3 characters in length\n '%2'\t\tFinds any values that end with 2\n '_2%3'\t\tFinds any values that have a 2 in the second position and end with a 3\n'2___3'\t\tFinds any values in a five-digit number that start with 2 and end with 3\n</pre>\n</html>");
        nameHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelpMouseExited(evt);
            }
        });

        nameHelp1.setText("[?]");
        nameHelp1.setToolTipText("Help");
        nameHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelp1MouseExited(evt);
            }
        });

        nameHelp2.setText("[?]");
        nameHelp2.setToolTipText("Help");
        nameHelp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelp2MouseExited(evt);
            }
        });

        facultyBox.setModel(facultyBoxModel);
        facultyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyBoxActionPerformed(evt);
            }
        });

        programmeBox.setModel(programmeBoxModel);

        paperCodeBox.setModel(paperCodeBoxModel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameHelp)
                                .addComponent(nameHelp1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(nameHelp2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programmeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paperCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(venueField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tableNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attendanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(warningMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addGap(13, 13, 13)))
                .addGap(73, 73, 73))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateField, icField, idField, nameField, tableNumberField, venueField});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {facultyBox, paperCodeBox, programmeBox});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(nameHelp)
                                .addComponent(jLabel15)
                                .addComponent(programmeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(venueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(icField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameHelp1)
                            .addComponent(jLabel14)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(attendanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameHelp2)
                            .addComponent(jLabel13)
                            .addComponent(sessionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tableNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paperCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchButton)
                    .addComponent(warningMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dateField, icField, idField, nameField, tableNumberField, venueField});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {facultyBox, paperCodeBox, programmeBox});

        examTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student IC", "Student ID", "Programme", "Faculty", "Paper Code", "Venue", "Date", "Session", "Status", "Attandance", "Table Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(examTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        searchButton1.setText("Search");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Programme: ");

        jLabel23.setText("Faculty:");

        jLabel24.setText("Paper Code:");

        idField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField1ActionPerformed(evt);
            }
        });

        icField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icField1jTextField2ActionPerformed(evt);
            }
        });

        nameField1.setToolTipText("");
        nameField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameField1.setName(""); // NOI18N
        nameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField1jTextField1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Student Name:");

        jLabel26.setText("Student IC:");

        jLabel27.setText("Student ID:");

        warningMessage1.setForeground(new java.awt.Color(255, 0, 0));

        nameHelp6.setText("[?]");
        nameHelp6.setToolTipText("Help");
        nameHelp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelp6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelp6MouseExited(evt);
            }
        });

        nameHelp7.setText("[?]");
        nameHelp7.setToolTipText("Help");
        nameHelp7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelp7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelp7MouseExited(evt);
            }
        });

        nameHelp8.setText("[?]");
        nameHelp8.setToolTipText("Help");
        nameHelp8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameHelp8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameHelp8MouseExited(evt);
            }
        });

        programmeBox2.setModel(programmeBoxModel);

        facultyBox2.setModel(facultyBoxModel);

        paperCodeBox2.setModel(paperCodeBoxModel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameHelp6)
                        .addComponent(nameHelp7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(nameHelp8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(facultyBox2, 0, 101, Short.MAX_VALUE)
                    .addComponent(paperCodeBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programmeBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(searchButton1)
                .addGap(11, 11, 11))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(warningMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {icField1, idField1, nameField1});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(nameHelp6)
                    .addComponent(jLabel22)
                    .addComponent(programmeBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(icField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameHelp7)
                    .addComponent(jLabel23)
                    .addComponent(facultyBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameHelp8)
                    .addComponent(jLabel24)
                    .addComponent(paperCodeBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(warningMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {icField1, idField1, nameField1});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {facultyBox2, paperCodeBox2, programmeBox2});

        markTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "RegNum", "Student IC", "Programme", "Faculty", "Paper Code", "Pratical", "Coursework"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(markTable);

        updateButton.setText("Save");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonjButton1ActionPerformed(evt);
            }
        });

        statusMessage.setText("          ");

        restoreButton.setText("Restore");
        restoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreButtonjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(statusMessage)
                        .addGap(96, 96, 96)
                        .addComponent(restoreButton)
                        .addGap(31, 31, 31)
                        .addComponent(updateButton)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(205, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {restoreButton, updateButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusMessage)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateButton)
                        .addComponent(restoreButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {restoreButton, updateButton});

        jScrollPane3.setViewportView(jPanel1);

        jTabbedPane1.addTab("tab2", jScrollPane3);

        jLabel4.setText("Exam Database Semester:");

        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAY/JUN" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GetData getData = new GetData(icField.getText(),nameField.getText(), idField.getText(),
                                        (String)statusBox.getSelectedItem(),(String)attendanceBox.getSelectedItem(), tableNumberField.getText(),
                                        (String)programmeBox.getSelectedItem(),(String)facultyBox.getSelectedItem(),
                                        dateField.getText(), (String)sessionBox.getSelectedItem(),
                                        (String)paperCodeBox.getSelectedItem(), "",
                                        venueField.getText(),""
                                        );
        warningMessage.setText("");
        ArrayList<GetData> list = null;
        
        tableModel = (DefaultTableModel) examTable.getModel();
        tableModel.setRowCount(0);
        
        try {
            list = getData.getDataFromTable();
            
            int i = 0;
            for(i = 0; i<list.size(); i++){
                tableModel.addRow(new Object[]{list.get(i).name, list.get(i).ic, list.get(i).regNum,
                                            list.get(i).progName, list.get(i).faculty, 
                                            list.get(i).paperCode, list.get(i).venueName,
                                            list.get(i).date, list.get(i).session, list.get(i).status,
                                            list.get(i).attendance, list.get(i).tableNum
                                            });
            }
        
        } catch (CustomException ex) {
            String message = ex.getMessage();
            warningMessage.setText(message);
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumberFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void nameHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelpMouseEntered
        // TODO add your handling code here:
        nameHelp.setText("<HTML><U>[?]</U></HTML>");
        nameHelp.setCursor(new Cursor(Cursor.HAND_CURSOR));
//        nameHelp.setDefaultCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_nameHelpMouseEntered

    private void nameHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelpMouseExited
        // TODO add your handling code here:
        nameHelp.setText("[?]");
    }//GEN-LAST:event_nameHelpMouseExited

    private void nameHelp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp1MouseEntered

    private void nameHelp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp1MouseExited

    private void nameHelp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp2MouseEntered

    private void nameHelp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp2MouseExited

    private void venueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venueFieldActionPerformed

    private void searchButton1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1jButton1ActionPerformed
        // TODO add your handling code here:
        GetData getData = new GetData(icField1.getText(),nameField1.getText(), idField1.getText(),
                                        "","","",
                                        (String)programmeBox2.getSelectedItem(), (String)facultyBox2.getSelectedItem(),
                                        "", "",
                                        (String)paperCodeBox2.getSelectedItem(), "",
                                        "",""
                                        );
        
        statusMessage.setText("");
        ArrayList<GetData> list = null;
        
        tableModel = (DefaultTableModel) markTable.getModel();
        tableModel.setRowCount(0);
        
        try {
            list = getData.getDataCheckMark();
            
            int i = 0;
            for(i = 0; i<list.size(); i++){
                tableModel.addRow(new Object[]{list.get(i).name, list.get(i).regNum, list.get(i).ic,
                                            list.get(i).progName, list.get(i).faculty, 
                                            list.get(i).paperCode,list.get(i).pratical,
                                            list.get(i).coursework
                                            });
            }
        
        } catch (CustomException ex) {
            String message = ex.getMessage();
            statusMessage.setText(message);
        }
    }//GEN-LAST:event_searchButton1jButton1ActionPerformed

    private void idField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField1ActionPerformed

    private void icField1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icField1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icField1jTextField2ActionPerformed

    private void nameField1jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField1jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField1jTextField1ActionPerformed

    private void nameHelp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp6MouseEntered

    private void nameHelp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp6MouseExited

    private void nameHelp7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp7MouseEntered

    private void nameHelp7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp7MouseExited

    private void nameHelp8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp8MouseEntered

    private void nameHelp8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelp8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameHelp8MouseExited

    private void updateButtonjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonjButton1ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this
               , "Confirm to save?"
               ,"Save"
               ,JOptionPane.OK_CANCEL_OPTION);
        GregorianCalendar calendar = new GregorianCalendar();

        if(confirm == JOptionPane.OK_OPTION){
        ArrayList<Object[]> listData = null;
        
        tableModel = (DefaultTableModel) markTable.getModel();
        
        for(int i = 0; i < markTable.getRowCount(); i++){
            
            new UpdateMark( (String)tableModel.getValueAt(i,1),
                            (String)tableModel.getValueAt(i,5),
                            (Integer)tableModel.getValueAt(i,6),
                            (Integer)tableModel.getValueAt(i,7)
                            ).setMark();

            

        }
         statusMessage.setText("Recent updated on "
                                + calendar.get(Calendar.HOUR)+":"
                                + calendar.get(Calendar.MINUTE)+":"
                                + calendar.get(Calendar.SECOND)+"  "
                                + calendar.get(Calendar.DATE) + " "
                                + months[calendar.get(Calendar.MONTH)]+ " "
                                + calendar.get(Calendar.YEAR)
                                + ""
                                );
        }
    }//GEN-LAST:event_updateButtonjButton1ActionPerformed

    private void nameHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameHelpMouseClicked
        // TODO add your handling code here:
        JFrame help = new JFrame("Help");
        

    }//GEN-LAST:event_nameHelpMouseClicked

    private void facultyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyBoxActionPerformed

    private void restoreButtonjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreButtonjButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this
               , "Confirm to restore to previous saved data?"
               ,"Restore"
               ,JOptionPane.OK_CANCEL_OPTION);

        if(confirm == JOptionPane.OK_OPTION){
        ArrayList<GetData> listTable = new ArrayList<>() ;
        tableModel = (DefaultTableModel) markTable.getModel();
        
            for(int i = 0; i < markTable.getRowCount(); i++){

                listTable.add(new GetData((String)tableModel.getValueAt(i,2),(String)tableModel.getValueAt(i,0),
                                            (String)tableModel.getValueAt(i,1),
                                            "","","",
                                            (String)tableModel.getValueAt(i,3), (String)tableModel.getValueAt(i,4),
                                            "", "",
                                            (String)tableModel.getValueAt(i,5), "",
                                            "",""
                                            ));
            }
            
            tableModel.setRowCount(0);
            ArrayList<GetData> listData = null; 
            
            for(int i = 0; i<listTable.size(); i++){
                try{
                    listData = listTable.get(i).getDataCheckMark();
                    tableModel.addRow(new Object[]{listData.get(0).name, listData.get(0).regNum, listData.get(0).ic,
                                                listData.get(0).progName, listData.get(0).faculty, 
                                                listData.get(0).paperCode,listData.get(0).pratical,
                                                listData.get(0).coursework
                                                });
                }catch (CustomException ex) {
                    String message = ex.getMessage();
                    statusMessage.setText(message);
                }
            }

        }
    }//GEN-LAST:event_restoreButtonjButton1ActionPerformed
    
    public void setComboBox(){
       ArrayList<String> list = new GetData().getList("Programme", "Name");
       
       //get the distinct programme list from database
       programmeBoxModel.addElement("");
       for(int i = 0; i<list.size(); i++){
           programmeBoxModel.addElement(list.get(i));
       }
       AutoCompletion.enable(statusBox);
       
       //get the distinct paperCode list from database
       list = new GetData().getList("PaperInfo", "PaperCode");
       
       paperCodeBoxModel.addElement("");
       for(int i = 0; i<list.size(); i++){
           paperCodeBoxModel.addElement(list.get(i));
       }
       
       //get the distinct programme list from database
       list = new GetData().getList("Programme", "Faculty");
       facultyBoxModel.addElement("");
       for(int i = 0; i<list.size(); i++){
           facultyBoxModel.addElement(list.get(i));
       }
       
       
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIapp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> attendanceBox;
    private javax.swing.JTextField dateField;
    private javax.swing.JTable examTable;
    private javax.swing.JComboBox<String> facultyBox;
    private javax.swing.JComboBox<String> facultyBox2;
    private javax.swing.JTextField icField;
    private javax.swing.JTextField icField1;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable markTable;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JLabel nameHelp;
    private javax.swing.JLabel nameHelp1;
    private javax.swing.JLabel nameHelp2;
    private javax.swing.JLabel nameHelp6;
    private javax.swing.JLabel nameHelp7;
    private javax.swing.JLabel nameHelp8;
    private javax.swing.JComboBox<String> paperCodeBox;
    private javax.swing.JComboBox<String> paperCodeBox2;
    private javax.swing.JComboBox<String> programmeBox;
    private javax.swing.JComboBox<String> programmeBox2;
    private javax.swing.JButton restoreButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JComboBox<String> sessionBox;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JLabel statusMessage;
    private javax.swing.JTextField tableNumberField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField venueField;
    private javax.swing.JLabel warningMessage;
    private javax.swing.JLabel warningMessage1;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables
}
